
$set	1

1	tsdog must be run as root\n

2	Can't get dog state

3	Dog timeout is outside the range %ldmS - %ldmS\n

4	Can't set dog timeout

5	Pat interval must be less than dog timeout (%ldmS)\n

6	Can't fork

7	A copy of tsdog is already running\n

8	Couldn't create lock file

9	Can't control dog

10	Can't set itimer

11	Can't pat dog

12	Can't turn dog off

13	Can't stop itimer

14	Failed to create signal mask

15	Failed to block signals

16	sigset SIGHUP failed

17	sigset SIGALRM failed

18	Can't get info for for RT class

19	Can't become RT process

20	tsdog [ patinterval=<interval> ] [ dogtimeout=<timeout> ] [ reset=enabled ]\n


$set	2

1	Getting dog state

2	watchdog=%s\nreset=%s\n

3	Getting alarm state

4	alarm%1.1d=%s\n

5	Setting watchdog %s, reset %s\n

6	Setting dog state

7	Setting alarm

8	Usage: tsctl status\n  or: tsctl <object>=<value> ...\n


$set	3

1	Failed to find '%s'\n

2	Found token %d ('%s'): value '%s'\n

3	Unrecognised argument

4	Inappropriate argument

5	Can't open device

6	Inappropriate command

7	Command interrupted

8	Command failed

9	Exiting with code %d\n


$set	4

1	tsdog must be run as root\n

2	Can't get dog state

3	Dog timeout is outside the range %ldmS - %ldmS\n

4	Can't set dog timeout

5	Pat interval must be less than dog timeout (%ldmS)\n

6	Can't fork

7	A copy of tsdog is already running\n

8	Couldn't create lock file

9	Can't control dog

10	Can't set itimer

11	Can't pat dog

12	Can't turn dog off

13	Can't stop itimer

14	Failed to create signal mask

15	Failed to block signals

16	sigset SIGHUP failed

17	sigset SIGALRM failed

18	Can't get info for for RT class

19	Can't become RT process

20	tsdog [ patinterval=<interval> ] [ dogtimeout=<timeout> ] [ reset=enabled ]\n


$set	5

1	tsdog must be run as root\n

2	Can't get dog state

3	Dog timeout is outside the range %ldmS - %ldmS\n

4	Can't set dog timeout

5	Pat interval must be less than dog timeout (%ldmS)\n

6	Can't fork

7	A copy of tsdog is already running\n

8	Couldn't create lock file

9	Can't control dog

10	Can't set itimer

11	Can't pat dog

12	Can't turn dog off

13	Can't stop itimer

14	Failed to create signal mask

15	Failed to block signals

16	sigset SIGHUP failed

17	sigset SIGALRM failed

18	Can't get info for for RT class

19	Can't become RT process

20	tsdog [ patinterval=<interval> ] [ dogtimeout=<timeout> ] [ reset=enabled ]\n


$set	6

1	Getting monitor valid mask

2	TSIOCWTMON error

3	TSIOCNBMON error

4	Usage: tsstate [ wait [ <object>=<value> ... ] ]\n


$set	7

1	Unlock ioctl failed

2	Usage: tsunlock\n

