#!/bin/sh
CLASSPATH=../po_file/:${TT_WS_ROOT}/src/filters/software_filters/software:${TT_WS_ROOT}/../transtech-build:${TT_WS_ROOT}/../transtech-build/utilities:${TT_WS_ROOT}/../transtech-build/filters:${TT_WS_ROOT}/build/filters.jar:${TT_WS_ROOT}/build/tt-common.jar
xDEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=58000"

export CLASSPATH
java ${DEBUG} -Xmx512m com.sun.tt.filters.software.SoftwareToXliff $@
