
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. /space/timf/transtech/utilities/dtd_doc_fragment/src/com/sun/tt/parsers/DTDDocFragmentParser/DTDDocFragmentParserVisitor.java */

package org.jvnet.olt.parsers.DTDDocFragmentParser;

public interface DTDDocFragmentParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
