/*
* CDDL HEADER START
*
* The contents of this file are subject to the terms of the
* Common Development and Distribution License (the "License").
* You may not use this file except in compliance with the License.
*
* You can obtain a copy of the license at LICENSE.txt
* or http://www.opensource.org/licenses/cddl1.php.
* See the License for the specific language governing permissions
* and limitations under the License.
*
* When distributing Covered Code, include this CDDL HEADER in each
* file and include the License file at LICENSE.txt.
* If applicable, add the following below this CDDL HEADER, with the
* fields enclosed by brackets "[]" replaced with your own identifying
* information: Portions Copyright [yyyy] [name of copyright owner]
*
* CDDL HEADER END
*/

/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/*
 * File:           XmlConfigHandler.java
 * Date:           06 February 2003  11:26
 *
 * @author  bpk1
 * @version generated by NetBeans XML module
 */
package org.jvnet.olt.filters.xml.xmlconfig;

import org.xml.sax.*;

public interface XmlConfigHandler extends ContentHandler {
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_config_element(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_noNamespaceSchemaLocation(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_schema(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_schema() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_public(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_config(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_config() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_file_type_description(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_generated_by(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_dtd(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_dtd() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_head(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_head() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_config_attribute(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_schemaLocation(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_identifier(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_identifier() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_namespace(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_file_type(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_system(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_last_modified_date(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_generated_date(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_body(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_body() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_author(final java.lang.String data, final Attributes meta) throws SAXException;
    
    public void endDocument() throws org.xml.sax.SAXException;
    
    public XmlConfig getXmlConfig();
      
}

