
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree&JavaCC: Do not edit this line. NonConformantSgmlTagParserConstants.java */
package org.jvnet.olt.filters.NonConformantSgmlTagParser;

public interface NonConformantSgmlTagParserConstants {

  int EOF = 0;
  int STAG = 1;
  int CLOSETAG = 2;
  int XMLETAG = 3;
  int ETAG = 4;
  int LETTER = 5;
  int NUM = 6;
  int NCNAMECHAR = 7;
  int PREFIX = 8;
  int NCNAME = 9;
  int EQ = 10;
  int STRING_LIT = 11;
  int UNQUOTED_STRING = 12;
  int WS = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\"</\"",
    "\"/>\"",
    "\">\"",
    "<LETTER>",
    "<NUM>",
    "<NCNAMECHAR>",
    "<PREFIX>",
    "<NCNAME>",
    "\"=\"",
    "<STRING_LIT>",
    "<UNQUOTED_STRING>",
    "<WS>",
  };

}
