/* Generated By:JJTree: Do not edit this line. /space/timf/olt-rc/open-language-tools/src/filters/non-conformant_sgml_tag_parser/src/org/jvnet/olt/filters/NonConformantSgmlTagParser/NonConformantSgmlTagParserVisitor.java */

package org.jvnet.olt.filters.NonConformantSgmlTagParser;

public interface NonConformantSgmlTagParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
