
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. /space/timf/transtech/utilities/messageformat_parser/src/com/sun/transtech/parsers/MessageFormatParser/MessageFormatParserTreeConstants.java */

package org.jvnet.olt.parsers.MessageFormatParser;

public interface MessageFormatParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTCONV = 1;
  public int JJTTYPE = 2;
  public int JJTSTYLE = 3;
  public int JJTWORDS = 4;
  public int JJTWS = 5;
  public int JJTEOF = 6;


  public String[] jjtNodeName = {
    "file",
    "conv",
    "type",
    "style",
    "words",
    "ws",
    "eof",
  };
}
