/*
* CDDL HEADER START
*
* The contents of this file are subject to the terms of the
* Common Development and Distribution License (the "License").
* You may not use this file except in compliance with the License.
*
* You can obtain a copy of the license at LICENSE.txt
* or http://www.opensource.org/licenses/cddl1.php.
* See the License for the specific language governing permissions
* and limitations under the License.
*
* When distributing Covered Code, include this CDDL HEADER in each
* file and include the License file at LICENSE.txt.
* If applicable, add the following below this CDDL HEADER, with the
* fields enclosed by brackets "[]" replaced with your own identifying
* information: Portions Copyright [yyyy] [name of copyright owner]
*
* CDDL HEADER END
*/

/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. SimpleNode.java */

package org.jvnet.olt.parsers.MessageFormatParser;

public class SimpleNode 
implements Node
{

  
  protected Node parent;
  protected Node[] children;
  protected int id;

  protected String m_nodeData = "";   //  A string to hold data about the node,
                                      //  normally token values.

  
  protected int m_beginLine   = -1;
  protected int m_beginColumn = -1;
  protected int m_endLine     = -1;
  protected int m_endColumn   = -1;

  public SimpleNode(int i) {
    id = i;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }
  
  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(MessageFormatParserVisitor visitor, Object data)  {
     data = visitor.visit(this, data);
     data = childrenAccept(visitor,data);
    return data;
  }

/** Accept the visitor. **/



  public Object childrenAccept(MessageFormatParserVisitor visitor, Object data) {
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        data = children[i].jjtAccept(visitor, data);
      }
    }
    return data;
  }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return MessageFormatParserTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
	SimpleNode n = (SimpleNode)children[i];
	if (n != null) {
	  n.dump(prefix + " ");
	}
      }
    }
  }

  public void setNodeData(String strData)
  {
    m_nodeData = strData;
  }

  public String getNodeData()
  {
    return m_nodeData;
  }

  public void setBeginPos(int beginLine, int beginColumn, boolean update)
  {
    if(((m_beginLine == -1) && (m_beginColumn == -1)) || update)
    {
      m_beginLine   = beginLine;
      m_beginColumn = beginColumn;
    }
  }

  public void setEndPos(int endLine, int endColumn, boolean update)
  {
    if(((m_endLine == -1) && (m_endColumn == -1)) || update)
    {
      m_endLine   = endLine;
      m_endColumn = endColumn;
    }
  }

  public int getBeginLine()
  {
    return m_beginLine;
  }

  public int getEndLine()
  {
    return m_endLine;
  }

  public int getBeginColumn()
  {
    return m_beginColumn;
  }

  public int getEndColumn()
  {
    return m_endColumn;
  }


  public int getType()
  {
    return id;
  }


}






