/*
* CDDL HEADER START
*
* The contents of this file are subject to the terms of the
* Common Development and Distribution License (the "License").
* You may not use this file except in compliance with the License.
*
* You can obtain a copy of the license at LICENSE.txt
* or http://www.opensource.org/licenses/cddl1.php.
* See the License for the specific language governing permissions
* and limitations under the License.
*
* When distributing Covered Code, include this CDDL HEADER in each
* file and include the License file at LICENSE.txt.
* If applicable, add the following below this CDDL HEADER, with the
* fields enclosed by brackets "[]" replaced with your own identifying
* information: Portions Copyright [yyyy] [name of copyright owner]
*
* CDDL HEADER END
*/

/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/*
 * XliffSplittingPrefsDialog.java
 *
 * Created on 24 September 2003, 15:23
 */

package org.jvnet.olt.editor.filesplit;

import org.jvnet.olt.editor.filefilters.XliffFileFilter;
import org.jvnet.olt.editor.filefilters.ZippedXliffFileFilter;
import org.jvnet.olt.editor.filefilters.WritableDirectoryFileFilter;
import org.jvnet.olt.xliff.XliffDocument;
import org.jvnet.olt.utilities.XliffZipFileIO;
import java.io.File;
import java.io.IOException;
import java.util.zip.ZipException;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 * This class handles gathering valid preferences for the file splitting operation
 * from the user.
 * @author  jc73554
 */
public class XliffSplittingPrefsDialog extends JDialog {
    
    private String defaultFileName;
    
    private XliffSplittingPrefs preferences;
    
    private String defaultSuffix;
    
    private int defaultModulus;
    
    private String defaultOutputDir;
    
    /** Creates new form XliffSplittingPrefsDialog */
    public XliffSplittingPrefsDialog(JFrame frame) {
        super(frame, true);
        preferences = null;
        defaultSuffix = "chunk";
        defaultModulus = 100;
        defaultOutputDir = "";
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel3;
        javax.swing.JLabel jLabel4;

        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputFileTextField = new javax.swing.JTextField();
        inputFileTextField.setText(defaultFileName);
        browseInputButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        suffixTextField = new javax.swing.JTextField();
        suffixTextField.setText(defaultSuffix);
        jLabel3 = new javax.swing.JLabel();
        segsPerFileTextField = new javax.swing.JTextField();
        segsPerFileTextField.setText("" + defaultModulus);
        jLabel4 = new javax.swing.JLabel();
        outputLocTextField = new javax.swing.JTextField();
        outputLocTextField.setText(defaultOutputDir);
        browseOutputLoc = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        setTitle(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("Set_splitting_preferences"));
        setFocusTraversalPolicy(getFocusTraversalPolicy());
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        okButton.setMnemonic('O');
        okButton.setText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("_OK"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setMnemonic('C');
        cancelButton.setText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("Cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel1.setLabelFor(inputFileTextField);
        jLabel1.setText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("Input_file:_"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel6.add(jLabel1, gridBagConstraints);

        inputFileTextField.setColumns(25);
        inputFileTextField.setToolTipText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("TheXLF_or_XLZ_file_to_be_split"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel6.add(inputFileTextField, gridBagConstraints);

        browseInputButton.setText("...");
        browseInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseInputButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel6.add(browseInputButton, gridBagConstraints);

        jLabel2.setText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("Suffix:_"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel6.add(jLabel2, gridBagConstraints);

        suffixTextField.setColumns(30);
        suffixTextField.setToolTipText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("A_suffix_to_append_to_the_names_of_the_output_files"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel6.add(suffixTextField, gridBagConstraints);

        jLabel3.setText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("Segments_per_file:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel6.add(jLabel3, gridBagConstraints);

        segsPerFileTextField.setColumns(25);
        segsPerFileTextField.setToolTipText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("The_number_of_XLIFF_translation_units_to_put_in_each_output_file"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel6.add(segsPerFileTextField, gridBagConstraints);

        jLabel4.setLabelFor(outputLocTextField);
        jLabel4.setText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("Output_directory:_"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel6.add(jLabel4, gridBagConstraints);

        outputLocTextField.setColumns(21);
        outputLocTextField.setToolTipText(org.jvnet.olt.editor.util.Bundle.getBundle("org/jvnet/olt/editor/filesplit/XliffSplittingPrefsDialog").getString("The_directory_to_store_the_output_files"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel6.add(outputLocTextField, gridBagConstraints);

        browseOutputLoc.setText("...");
        browseOutputLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOutputLocActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel6.add(browseOutputLoc, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        jPanel6.add(jPanel7, gridBagConstraints);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-432)/2, (screenSize.height-241)/2, 432, 241);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        handleCancelButton();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        handleOkButton();
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void browseOutputLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOutputLocActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        WritableDirectoryFileFilter dirFilter = new WritableDirectoryFileFilter();
        
        fileChooser.addChoosableFileFilter(dirFilter);
        fileChooser.setFileFilter(dirFilter);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(null);

        int iReturn = fileChooser.showDialog(this, "Select");
        if(iReturn == JFileChooser.APPROVE_OPTION) {
            outputLocTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseOutputLocActionPerformed
    
    private void browseInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseInputButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        ZippedXliffFileFilter zippedFilter = new ZippedXliffFileFilter();
        
        fileChooser.addChoosableFileFilter(zippedFilter);
        fileChooser.addChoosableFileFilter(new XliffFileFilter());
        fileChooser.setFileFilter(zippedFilter);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(null);

        int iReturn = fileChooser.showDialog(this, "Select");
        if(iReturn == JFileChooser.APPROVE_OPTION) {
            inputFileTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseInputButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //  Treat this as a cancel.
        handleCancelButton();
    }//GEN-LAST:event_exitForm
    
    public XliffSplittingPrefs getPreferences() {
        return preferences;
    }
    
    public void setDefaultFilename(java.lang.String defaultFileName) {
        this.defaultFileName = defaultFileName;
    }
    
    protected boolean testFormValues(File inputFile, File outputDir, java.lang.String suffix, int numSegs) {
        String message = "";
        if( !(inputFile.exists() && inputFile.isFile() && inputFile.canRead()) ) {
            //  Display error message
            message = "The input file chosen is not a readable file. Please select a readable file.";
            JOptionPane.showMessageDialog(this, message, "Invalid form values", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if( !(outputDir.exists() && outputDir.isDirectory() && outputDir.canWrite()) ) {
            //  Display error message
            message = "The output location selected is not a writable directory. Please select a writable directory.";
            JOptionPane.showMessageDialog(this, message, "Invalid form values", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(numSegs <= 0) {
            //  Display error message
            message = "The number of segments per file that has been specified is less than one. This value needs to be one or more.";
            JOptionPane.showMessageDialog(this, message, "Invalid form values", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        //  Add a possible test for the contents of the suffix here.
        
        return true;
    }
    
    protected XliffDocument openInputFile(File inputFile) throws IOException, ZipException {
        XliffZipFileIO zipIO = new XliffZipFileIO(inputFile);
        return zipIO.toXliffDocument();
    }
    
    protected void handleOkButton() {
        //  Set the defaults.
        defaultFileName = inputFileTextField.getText();
        defaultOutputDir = outputLocTextField.getText();
        defaultSuffix = suffixTextField.getText();
        
        try {
            defaultModulus = Integer.parseInt(segsPerFileTextField.getText());
        }
        catch(NumberFormatException numFormEx) {
            String msg = "The value specified for 'Segments per file' does not appear to be a number.";
            JOptionPane.showMessageDialog(this, msg, "Invalid form input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        File inputFile = new File(defaultFileName);
        File outputDirectory = new File(defaultOutputDir);
        
        if(testFormValues(inputFile, outputDirectory, defaultSuffix, defaultModulus)) {
            XliffDocument xliffDoc = null;
            String message = "";
            try {
                xliffDoc = openInputFile(inputFile);
            }
            catch(ZipException zipEx) {
                //  Display message and exit
                message = "The XLZ file that you selected appears to be corrupt. Please check the file and try again.";
                JOptionPane.showMessageDialog(this, message, "Read error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            catch(IOException ioEx) {
                //  Display message and exit
                message = "The was an unexpected error reading the input file that you selected. Please check the file and try again.";
                JOptionPane.showMessageDialog(this, message, "Read error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            preferences = new XliffSplittingPrefs();
            preferences.setXliffDocument(xliffDoc);
            preferences.setOutputLoc(outputDirectory);
            preferences.setSegmentNum(defaultModulus);
            preferences.setSuffix(defaultSuffix);
            
            this.dispose();
        }
    }
    
    protected void handleCancelButton() {
        //  Exit the dialog and set the prefs object to null.
        preferences = null;
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseInputButton;
    private javax.swing.JButton browseOutputLoc;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField inputFileTextField;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField outputLocTextField;
    private javax.swing.JTextField segsPerFileTextField;
    private javax.swing.JTextField suffixTextField;
    // End of variables declaration//GEN-END:variables
    
}
