
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. /space/timf/transtech/utilities/printf_parser/src/com/sun/transtech/parsers/PrintfParser/PrintfParserVisitor.java */

package org.jvnet.olt.parsers.PrintfParser;

public interface PrintfParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
