/* Generated By:JJTree: Do not edit this line. /space/timf/olt-rc/open-language-tools/src/filters/software_filters/java_props_file/org/jvnet/olt/parsers/PropsFileParser/PropsFileParserTreeConstants.java */

package org.jvnet.olt.parsers.PropsFileParser;

public interface PropsFileParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTMESSAGE = 1;
  public int JJTKEY = 2;
  public int JJTEQUALS = 3;
  public int JJTVALUE = 4;
  public int JJTVALUE_NO_LAYOUT = 5;
  public int JJTVALUE_ON_MANY = 6;
  public int JJTSENTENCE = 7;
  public int JJTWORD = 8;
  public int JJTWHITE_SPACE = 9;
  public int JJTEQUALS_CHAR = 10;
  public int JJTSLASHNEWLINE = 11;
  public int JJTBLANK_LINE = 12;
  public int JJTSLASHNEWLINE_STORED = 13;
  public int JJTSLASH_CHAR = 14;
  public int JJTNEWLINE = 15;
  public int JJTCOMMENT_CHAR = 16;
  public int JJTLC_COMMENT_CHAR = 17;
  public int JJTTMC_COMMENT_CHAR = 18;
  public int JJTNORMAL_COMMENT_BLOCK = 19;
  public int JJTNORMAL_COMMENT = 20;
  public int JJTLC_COMMENT_BLOCK = 21;
  public int JJTLC_COMMENT = 22;
  public int JJTTMC_COMMENT_BLOCK = 23;
  public int JJTTMC_COMMENT = 24;


  public String[] jjtNodeName = {
    "file",
    "message",
    "key",
    "equals",
    "value",
    "value_no_layout",
    "value_on_many",
    "sentence",
    "word",
    "white_space",
    "equals_char",
    "slashnewline",
    "blank_line",
    "slashnewline_stored",
    "slash_char",
    "newline",
    "comment_char",
    "lc_comment_char",
    "tmc_comment_char",
    "normal_comment_block",
    "normal_comment",
    "lc_comment_block",
    "lc_comment",
    "tmc_comment_block",
    "tmc_comment",
  };
}
