
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. /space/timf/transtech/src/filters/software_filters/rep_file/com/sun/tmc/parsers/RepFileParser/RepFileParserVisitor.java */

package org.jvnet.olt.parsers.RepFileParser;

public interface RepFileParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
