
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.10.08 at 01:50:51 BST 
//


package org.jvnet.olt.filters.xliffsubsegment.xliff;

public interface AltTrans {


    /**
     * Gets the value of the tool property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTool();

    /**
     * Sets the value of the tool property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTool(java.lang.String value);

    /**
     * Gets the value of the exstyle property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExstyle();

    /**
     * Sets the value of the exstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExstyle(java.lang.String value);

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFont();

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFont(java.lang.String value);

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTs();

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTs(java.lang.String value);

    /**
     * Gets the value of the helpId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getHelpId();

    /**
     * Sets the value of the helpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setHelpId(java.lang.String value);

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getStyle();

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setStyle(java.lang.String value);

    /**
     * Gets the value of the resname property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getResname();

    /**
     * Sets the value of the resname property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setResname(java.lang.String value);

    /**
     * Gets the value of the cssStyle property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCssStyle();

    /**
     * Sets the value of the cssStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCssStyle(java.lang.String value);

    /**
     * Gets the value of the menuName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMenuName();

    /**
     * Sets the value of the menuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMenuName(java.lang.String value);

    /**
     * Gets the value of the crc property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCrc();

    /**
     * Sets the value of the crc property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCrc(java.lang.String value);

    /**
     * Gets the value of the menuOption property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMenuOption();

    /**
     * Sets the value of the menuOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMenuOption(java.lang.String value);

    /**
     * Gets the value of the extradata property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExtradata();

    /**
     * Sets the value of the extradata property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExtradata(java.lang.String value);

    /**
     * Gets the value of the extype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExtype();

    /**
     * Sets the value of the extype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExtype(java.lang.String value);

    /**
     * Gets the value of the xmlSpace property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getXmlSpace();

    /**
     * Sets the value of the xmlSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setXmlSpace(java.lang.String value);

    /**
     * Gets the value of the restype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRestype();

    /**
     * Sets the value of the restype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRestype(java.lang.String value);

    /**
     * Gets the value of the menu property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMenu();

    /**
     * Sets the value of the menu property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMenu(java.lang.String value);

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getOrigin();

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setOrigin(java.lang.String value);

    /**
     * Gets the value of the xmlLang property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getXmlLang();

    /**
     * Sets the value of the xmlLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setXmlLang(java.lang.String value);

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDatatype();

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDatatype(java.lang.String value);

    /**
     * Gets the value of the coord property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCoord();

    /**
     * Sets the value of the coord property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCoord(java.lang.String value);

    /**
     * Gets the value of the matchQuality property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMatchQuality();

    /**
     * Sets the value of the matchQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMatchQuality(java.lang.String value);

    /**
     * Gets the value of the Content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.PropGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Note}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.ContextGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Source}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Target}
     * 
     */
    java.util.List getContent();

}
