
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.10.08 at 01:50:51 BST 
//


package org.jvnet.olt.filters.xliffsubsegment.xliff;

public interface BinSource {


    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTs();

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTs(java.lang.String value);

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link org.jvnet.olt.filters.xliffsubsegment.xliff.InternalFile}
     *     {@link org.jvnet.olt.filters.xliffsubsegment.xliff.ExternalFile}
     */
    java.lang.Object getContent();

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.jvnet.olt.filters.xliffsubsegment.xliff.InternalFile}
     *     {@link org.jvnet.olt.filters.xliffsubsegment.xliff.ExternalFile}
     */
    void setContent(java.lang.Object value);

}
