
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.10.08 at 01:50:51 BST 
//


package org.jvnet.olt.filters.xliffsubsegment.xliff;

public interface ExternalFile {


    /**
     * Gets the value of the crc property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCrc();

    /**
     * Sets the value of the crc property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCrc(java.lang.String value);

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getHref();

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setHref(java.lang.String value);

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUid();

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUid(java.lang.String value);

}
