
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.10.08 at 01:50:51 BST 
//


package org.jvnet.olt.filters.xliffsubsegment.xliff;

public interface Header {


    /**
     * Gets the value of the Content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.PropGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Note}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.PhaseGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.CountGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Reference}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Skl}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Glossary}
     * 
     */
    java.util.List getContent();

}
