
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.10.08 at 01:50:51 BST 
//


package org.jvnet.olt.filters.xliffsubsegment.xliff;

public interface TransUnit {


    /**
     * Gets the value of the maxheight property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMaxheight();

    /**
     * Sets the value of the maxheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMaxheight(java.lang.String value);

    /**
     * Gets the value of the exstyle property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExstyle();

    /**
     * Sets the value of the exstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExstyle(java.lang.String value);

    /**
     * Gets the value of the helpId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getHelpId();

    /**
     * Sets the value of the helpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setHelpId(java.lang.String value);

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getStyle();

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setStyle(java.lang.String value);

    /**
     * Gets the value of the resname property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getResname();

    /**
     * Sets the value of the resname property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setResname(java.lang.String value);

    /**
     * Gets the value of the menuOption property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMenuOption();

    /**
     * Sets the value of the menuOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMenuOption(java.lang.String value);

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getApproved();

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setApproved(java.lang.String value);

    /**
     * Gets the value of the extradata property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExtradata();

    /**
     * Sets the value of the extradata property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExtradata(java.lang.String value);

    /**
     * Gets the value of the maxbytes property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMaxbytes();

    /**
     * Sets the value of the maxbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMaxbytes(java.lang.String value);

    /**
     * Gets the value of the phaseName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPhaseName();

    /**
     * Sets the value of the phaseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPhaseName(java.lang.String value);

    /**
     * Gets the value of the restype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRestype();

    /**
     * Sets the value of the restype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRestype(java.lang.String value);

    /**
     * Gets the value of the sizeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSizeUnit();

    /**
     * Sets the value of the sizeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSizeUnit(java.lang.String value);

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDatatype();

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDatatype(java.lang.String value);

    /**
     * Gets the value of the minbytes property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMinbytes();

    /**
     * Sets the value of the minbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMinbytes(java.lang.String value);

    /**
     * Gets the value of the minheight property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMinheight();

    /**
     * Sets the value of the minheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMinheight(java.lang.String value);

    /**
     * Gets the value of the charclass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCharclass();

    /**
     * Sets the value of the charclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCharclass(java.lang.String value);

    /**
     * Gets the value of the maxwidth property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMaxwidth();

    /**
     * Sets the value of the maxwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMaxwidth(java.lang.String value);

    /**
     * Gets the value of the Content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.PropGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Note}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.ContextGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.CountGroup}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.AltTrans}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Source}
     * {@link org.jvnet.olt.filters.xliffsubsegment.xliff.Target}
     * 
     */
    java.util.List getContent();

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFont();

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFont(java.lang.String value);

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTs();

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTs(java.lang.String value);

    /**
     * Gets the value of the reformat property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getReformat();

    /**
     * Sets the value of the reformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setReformat(java.lang.String value);

    /**
     * Gets the value of the cssStyle property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCssStyle();

    /**
     * Sets the value of the cssStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCssStyle(java.lang.String value);

    /**
     * Gets the value of the menuName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMenuName();

    /**
     * Sets the value of the menuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMenuName(java.lang.String value);

    /**
     * Gets the value of the extype property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExtype();

    /**
     * Sets the value of the extype property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExtype(java.lang.String value);

    /**
     * Gets the value of the xmlSpace property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getXmlSpace();

    /**
     * Sets the value of the xmlSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setXmlSpace(java.lang.String value);

    /**
     * Gets the value of the translate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getTranslate();

    /**
     * Sets the value of the translate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setTranslate(java.lang.String value);

    /**
     * Gets the value of the menu property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMenu();

    /**
     * Sets the value of the menu property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMenu(java.lang.String value);

    /**
     * Gets the value of the minwidth property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMinwidth();

    /**
     * Sets the value of the minwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMinwidth(java.lang.String value);

    /**
     * Gets the value of the coord property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCoord();

    /**
     * Sets the value of the coord property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCoord(java.lang.String value);

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

}
