<html>
<table border="1">
	<tr>
		<td><em>Component</em></td>
		<td>UNIX version</td>
		<td>win32 version</td>
	</tr>
	<tr>
		<td>Open Language Tools XLIFF Translation Editor</td>
		<td>
              <a href="https://open-language-tools.dev.java.net/files/documents/3451/141407/transeditor_v1_3_0_lite_unix.jar">v1.3.0 (lite installer, 7.1MB)</a>
              <a href="https://open-language-tools.dev.java.net/files/documents/3451/141409/transeditor_v1_3_0_unix.tar.gz">v1.3.0 (full installer incl. spell checker, 36MB)</a>
        </td>
        <td>
              <a href="https://open-language-tools.dev.java.net/files/documents/3451/141408/transeditor_v1_3_0_lite_win.jar">v1.3.0 (lite installer, 7.1MB)</a>
              <a href="https://open-language-tools.dev.java.net/files/documents/3451/141410/transeditor_v1_3_0_win.zip">v1.3.0 (full installer incl. spell checker, 31MB)</a>
        </td>
	</tr>
	<tr>
		<td>Open Language Tools XLIFF Filters</td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/47026/xliff_filters_v1_2_7_unix.tar.gz">xliff_filters_v1_2_7_unix.tar.gz</a></td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/47027/xliff_filters_v1_2_7_win.zip">xliff_filters_v1_2_7_win.zip</a></td>

	</tr>
</table>
<center>
Latest XLIFF Editor User's Guide as 
<a href="https://open-language-tools.dev.java.net/files/documents/3451/15203/OLT_XLIFF_Translation_Editor_Manual.pdf">PDF</a></center>
</html>