<html>
<table border="1">
	<tr>
		<td><em>Component</em></td>
		<td>UNIX version</td>
		<td>win32 version</td>
	</tr>
	<tr>
		<td>Open Language Tools XLIFF Translation Editor</td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/37456/transeditor_v1_2_5_unix.tar.gz">transeditor_v1_2_5_unix.tar.gz</a></td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/37457/transeditor_v1_2_5_win.zip">transeditor_v1_2_5_win.zip</a></td>
	</tr>
	<tr>
		<td>Open Language Tools XLIFF Filters</td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/37458/xliff_filters_v1_2_5_unix.tar.gz">xliff_filters_v1_2_5_unix.tar.gz</a></td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/37459/xliff_filters_v1_2_5_win.zip">xliff_filters_v1_2_5_win.zip</a></td>
	</tr>
</table>
<center>
<a href="https://open-language-tools.dev.java.net/source/browse/open-language-tools/src/transeditor/docs/OLT_XLIFF_Translation_Editor_Manual_1_0.pdf?rev=1.2.4.5&only_with_tag=EDITOR_1_2_0&view=auto&content-type=text/vnd.viewcvs-markup">Latest XLIFF Editor User's Guide</a>
</center>
</html>
