<html>
<table border="1">
	<tr>
		<td><em>Component</em></td>
		<td>UNIX version</td>
		<td>win32 version</td>
	</tr>
	<tr>
		<td>Open Language Tools XLIFF Translation Editor</td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/46489/transeditor_v1_2_7_unix.tar.gz">transeditor_v1_2_7_unix.tar.gz</a></td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/46490/transeditor_v1_2_7_win.zip">transeditor_v1_2_7_win.zip</a></td>
	</tr>
	<tr>
		<td>Open Language Tools XLIFF Filters</td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/47026/xliff_filters_v1_2_7_unix.tar.gz">xliff_filters_v1_2_7_unix.tar.gz</a></td>
		<td><a href="https://open-language-tools.dev.java.net/files/documents/3451/47027/xliff_filters_v1_2_7_win.zip">xliff_filters_v1_2_7_win.zip</a></td>

	</tr>
</table>
<center>
Latest XLIFF Editor User's Guide as <a href="https://open-language-tools.dev.java.net/source/browse/open-language-tools/src/transeditor/docs/OLT_XLIFF_Translation_Editor_Manual_1_0.pdf?rev=1.2.4.5&only_with_tag=EDITOR_1_2_0&view=auto&content-type=text/vnd.viewcvs-markup">PDF</a></center>
</html>
