
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. /space/timf/transtech/src/filters/software_filters/po_file/com/sun/tmc/parsers/POFileParser/POFileParserTreeConstants.java */

package org.jvnet.olt.parsers.POFileParser;

public interface POFileParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTLC_COMMENT_HACK = 1;
  public int JJTTMC_COMMENT_HACK = 2;
  public int JJTCOMMENT_HACK = 3;
  public int JJTWS_HACK = 4;
  public int JJTNEWLINE_HACK = 5;
  public int JJTMESSAGE = 6;
  public int JJTMESSAGE_ID = 7;
  public int JJTMSGID_HACK = 8;
  public int JJTMSGID_TEXT = 9;
  public int JJTMESSAGE_STRING = 10;
  public int JJTMSGSTR_HACK = 11;
  public int JJTMSGSTR_TEXT = 12;
  public int JJTMSGSTR_UNFORMATTED_TEXT = 13;
  public int JJTMESSAGE_LINE = 14;
  public int JJTDOMAIN = 15;
  public int JJTDOMAIN_HACK = 16;
  public int JJTDOMAIN_TEXT = 17;
  public int JJTMSGID_PLURAL_HACK = 18;
  public int JJTMSGSTR_PLURAL_HACK = 19;


  public String[] jjtNodeName = {
    "file",
    "lc_comment_hack",
    "tmc_comment_hack",
    "comment_hack",
    "ws_hack",
    "newline_hack",
    "message",
    "message_id",
    "msgid_hack",
    "msgid_text",
    "message_string",
    "msgstr_hack",
    "msgstr_text",
    "msgstr_unformatted_text",
    "message_line",
    "domain",
    "domain_hack",
    "domain_text",
    "msgid_plural_hack",
    "msgstr_plural_hack",
  };
}
