#!/bin/sh

CLASSPATH=../cvs/utilities/jars/junit.jar:../transtech-build:../transtech-build-tests:.

export CLASSPATH

java -classpath ${CLASSPATH} junit.textui.TestRunner org.jvnet.olt.xliff_tmx_converter.XliffToTmxConverterTestSuite
