#!/bin/sh
CLASSPATH=${TT_WS_ROOT}/build/formatting.jar:${TT_WS_ROOT}/build/tt-common.jar:${TT_WS_ROOT}/build/filters
export CLASSPATH
xDEBUG="-Xint -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"
java ${DEBUG} com.sun.tt.filters.jsp.JspToXliff $@
