#!/bin/sh
CLASSPATH=${TT_WS_ROOT}/build/tt-common.jar:${TT_WS_ROOT}/build/filters:${TT_WS_ROOT}/utilities/jars/xerces2.jar:${TT_WS_ROOT}/utilities/jars/dtdparser121.jar
export CLASSPATH
xDEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=58000"

java -Xmx512m ${DEBUG} com.sun.transtech.filters.xml.XmlToXliff /space/timf/suntrans2-dtds/xml-config.dtd /space/timf/suntrans2-dtds/xml-filter-config $1 en-US /space/timf/suntrans2-dtds/empty.dtd
