/*
 * SpellCheckerDialog.java
 *
 * Created on November 27, 2006, 10:08 AM
 */

package org.jvnet.olt.editor.translation;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import org.jvnet.olt.editor.spellchecker.Suggestion;

/**
 *
 * @author  boris
 */
public class SpellCheckerDialog extends javax.swing.JDialog {    
    public enum Result { IGNORE, IGNORE_ALL, CHANGE, CHANGE_ALL, CANCEL,ADD };
    
    private DefaultListModel listModel;
    
    private Suggestion selectedSuggestion;
    
    private Result result = Result.CANCEL;
    
    private boolean enableChanges;
    /** Creates new form SpellCheckerDialog */
    public SpellCheckerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        listModel = new DefaultListModel();
        
        initComponents();
        
        selectionChanged(false);
        
        Style def = StyleContext.getDefaultStyleContext().getStyle(StyleContext.DEFAULT_STYLE);
        Style regular = textPane.addStyle("bold", def);
        StyleConstants.setBold(regular,true);
        StyleConstants.setForeground(regular,Color.RED);
        
        setTitle("Spellchecker");
    }

    DefaultListModel getListModel(){
        return listModel;
    }
    
    public void setSuggestions(Suggestion[] sugs){
        listModel.clear();
        
        if(sugs == null)
            return;
        
        for(Suggestion s:sugs)
            listModel.addElement(s);
        
        if(sugs.length > 0){
            suggestionsList.setSelectedIndex(0);
            selectionChanged(true);
        
        }
    }
    
    public void setWord(String word){        
        textPane.setText(word);
    }
    
    public void setSelection(int start,int end){
        
        Style regular = textPane.getStyle("bold");
        textPane.getStyledDocument().setCharacterAttributes(start,end,regular,false);
        
    }
    
    public void enableChanges(boolean enbleChngs){
        changeButton.setEnabled(enbleChngs);
        
        this.enableChanges = enbleChngs;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionsList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        ignoreAllButton = new javax.swing.JButton();
        ignoreButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        changeAllButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Not in dictionary:");

        suggestionsList.setModel(getListModel());
        suggestionsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                suggestionsListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(suggestionsList);

        jLabel2.setText("Suggestions:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        ignoreAllButton.setText("Ignore All");
        ignoreAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreAllButtonActionPerformed(evt);
            }
        });

        ignoreButton.setText("Ignore");
        ignoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreButtonActionPerformed(evt);
            }
        });

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        changeAllButton.setText("Change All");
        changeAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAllButtonActionPerformed(evt);
            }
        });

        textPane.setEditable(false);
        jScrollPane2.setViewportView(textPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(307, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(381, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ignoreAllButton)
                            .add(ignoreButton)
                            .add(addButton)
                            .add(changeButton)
                            .add(changeAllButton)
                            .add(cancelButton))
                        .addContainerGap())))
        );

        layout.linkSize(new java.awt.Component[] {addButton, cancelButton, changeAllButton, changeButton, ignoreAllButton, ignoreButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(ignoreButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ignoreAllButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addButton))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(changeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(changeAllButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 98, Short.MAX_VALUE)
                        .add(cancelButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suggestionsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_suggestionsListValueChanged
        int idx = suggestionsList.getSelectedIndex();
        
        selectionChanged(idx != -1);
        selectedSuggestion = idx == -1 ? null : (Suggestion)listModel.elementAt(idx);
    }//GEN-LAST:event_suggestionsListValueChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        result = Result.CANCEL;
        
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void changeAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAllButtonActionPerformed
        result = Result.CHANGE_ALL;
        setVisible(false);
        
    }//GEN-LAST:event_changeAllButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        result = Result.CHANGE;
        setVisible(false);

    }//GEN-LAST:event_changeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        result = Result.ADD;
        setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void ignoreAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreAllButtonActionPerformed
        result = Result.IGNORE_ALL;
        setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_ignoreAllButtonActionPerformed

    private void ignoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreButtonActionPerformed
        result = Result.IGNORE;
        setVisible(false);
    }//GEN-LAST:event_ignoreButtonActionPerformed

    private void selectionChanged(boolean b) {
        if(b && enableChanges){
            changeButton.setEnabled(b);
        }
        changeAllButton.setEnabled(b);
    }

    public Result getResult() {
        return result;
    }

    public Suggestion getSelectedSuggestion(){
        return selectedSuggestion;
    }
    
    public void setStatusText(String status){
        statusLabel.setText(status);
    }

    void resetState() {
        this.result = Result.CANCEL;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changeAllButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton ignoreAllButton;
    private javax.swing.JButton ignoreButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JList suggestionsList;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
    
}
