/* Generated By:JavaCC: Do not edit this line. RemoveTagProtectionConstants.java */
package org.jvnet.olt.soxliff_backconv;

public interface RemoveTagProtectionConstants {

  int EOF = 0;
  int WS = 1;
  int SUPPORTED_TAG = 2;
  int TAG = 3;
  int OTHER = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WS>",
    "<SUPPORTED_TAG>",
    "<TAG>",
    "<OTHER>",
    "\"<\"",
  };

}
