#!/bin/bash
export CLASSPATH=../classes
xLOGGING="-Djava.util.logging.config.file=/export/home/backup/XliffBackConverter/logging.properties"

java ${LOGGING}  -classpath ${CLASSPATH} com.sun.transtech.parsers.mapping.SuntransMappingFile $@
