
/*
 * Copyright  2005 Sun Microsystems, Inc. 
 * All rights reserved Use is subject to license terms.
 *
 */

/* Generated By:JJTree: Do not edit this line. /space/timf/transtech/utilities/non-conformant_sgml_doc_fragment/src/com/sun/tt/filters/NonConformantSgmlDocFragmentParser/NonConformantSgmlDocFragmentParserVisitor.java */

package org.jvnet.olt.filters.NonConformantSgmlDocFragmentParser;

public interface NonConformantSgmlDocFragmentParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
